test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -9,23 +9,50 @@ on:
       - 'ga-ignore-*'
 
 jobs:
-  check_coding_style:
+  check_program_compilation:
     runs-on: ubuntu-latest
-    container: ghcr.io/epitech/coding-style-checker:latest
+    container: epitechcontent/epitest-docker
     steps:
       - name: Checkout code
-        uses: actions/checkout@master
-      - name: Check coding style
+        uses: actions/checkout@v3
+      - name: Compile program
+        run: make
+        timeout-minutes: 2
+      - name: Clean up
+        run: make clean
+      - name: Check executables
         run: |
-            input=/tmp/coding-style-reports.log
-            while IFS= read -r -a line; do
-                fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
-                echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
-            done < $input
+          for executable in ${EXECUTABLES//,/ }; do
+            if [ ! -x "$executable" ]; then
+              echo "::error file=$executable,::Executable not found or not executable"
+              exit 1
+            fi
+          done
 
-      - name: banana
-        run: |
-          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
-          if [ $NB_ERROR -gt 0 ]; then
-            exit 1
-          fi
+  run_tests:
+    needs: check_program_compilation
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Run tests
+        run: make tests_run
+        timeout-minutes: 2
+
+  push_to_mirror:
+    if: github.event_name == 'push'
+    needs: run_tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+            fetch-depth: 0
+      - name: Mirror repository
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ vars.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
