test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -13,30 +13,29 @@ jobs:
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-        - name: Checkout GitHub repository
-          uses: actions/checkout@master
-        - name: Execute coding style check
-          run: ./check.sh . /tmp
-        - name: parsing for annontations
-          run: |
-            log_file="/tmp/coding-style-reports.log"
-            while IFS= read -r line; do
-              file=$(echo "$line" | cut -d':' -f1)
-              line_number=$(echo "$line" | cut -d':' -f2)
-              title=$(echo "$line" | cut -d':' -f3)
-              detail=$(echo "$line" | cut -d':' -f4)
-              echo "::error title=$title coding style error,file=$file,line=$line_number::$detail"
-            done < "$log_file"
 
-        - name: errors count
-          run: |
-            errors_count=$(wc -l < /tmp/coding-style-reports.log)
-            if [ "$errors_count" -gt 0 ]; then
-              echo "Found $errors_count coding style errors."
-              exit 1
-            else
-              echo "No coding style errors found."
-            fi
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ''
+      - name: Run coding-style
+        run: check.sh . /tmp
+      - name: Create annotation for coding-style errors
+        run: |
+          log_file="/tmp/coding-style-reports.log"
+          while IFS= read -r line; do
+            file=$(echo "$line" | cut -d':' -f1)
+            line_number=$(echo "$line" | cut -d':' -f2)
+            title=$(echo "$line" | cut -d':' -f3)
+            detail=$(echo "$line" | cut -d':' -f4)
+            echo "::error title=$title coding style error,file=$file,line=$line_number::$detail"
+          done < "$log_file"
+      - name: Report bananaresult and fail if errors found
+        run: |
+          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            exit 1
+          fi
 
   check_program_compilation:
     needs: check_coding_style
@@ -50,11 +49,11 @@ jobs:
         timeout-minutes: 2
       - name: Clean up
         run: make clean
-      - name: binary
+      - name: Check executables
         run: |
-          for executable in $EXECUTABLES; do
-            if [[ ! -x "$file" ]]; then
-              echo "Error: '$file' not executable or missing."
+          for executable in ${EXECUTABLES//,/ }; do
+            if [ ! -x "$executable" ]; then
+              echo "::error file=$executable,::Executable not found or not executable"
               exit 1
             fi
           done
